# CHAPTER 5. Getting Started with pandas

- Data structures with labeled axes supporting automatic or explicit data alignment.
This prevents common errors resulting from misaligned data and working with
differently-indexed data coming from different sources.
- Integrated time series functionality.
- The same data structures handle both time series data and non-time series data.
- Arithmetic operations and reductions (like summing across an axis) would pass
on the metadata (axis labels).
- Flexible handling of missing data.
- Merge and other relational operations found in popular database databases (SQL-
based, for example).

In [1]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

## Introduction to pandas Data Structures
### Series

In [2]:
obj = Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [12]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

- If you need data contained in a python dict, you can create a Series based on the dict data as well

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [21]:
obj3 = Series(sdata)

In [22]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [23]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [24]:
obj4 = Series(sdata, index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

- Series also has these as instance methods

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj

In [36]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

- A DataFrame represents a tabular, spreadsheet-like data structure containing an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.) 
- The DataFrame has both a row and column index

In [11]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [12]:
frame = DataFrame(data)

In [13]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [14]:
print(frame)

   pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002


In [41]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [42]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
         index=['one', 'two', 'three', 'four', 'five'])

In [43]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [44]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [45]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [46]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [47]:
frame2.ix['three']

/home/sooseok/Documents/.venv3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [48]:
frame2['debt'] = 16.5

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [50]:
frame2['debt'] = np.arange(5.)

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

- When assigning lists or arrays to a column, the value’s length must match the length of the DataFrame. If you assign a Series , it will be instead conformed exactly to the DataFrame’s index, inserting missing values in any holes

In [52]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [53]:
frame2['debt'] = val

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [55]:
frame2['eastern'] = frame2.state == 'Ohio'

In [56]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [57]:
del frame2['eastern']

In [58]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [59]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

- If passed to DataFrame, it will interpret the outer dict keys as the columns and the inner keys as the row indices

In [60]:
frame3 = DataFrame(pop)

In [61]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [62]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [63]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [64]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [65]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [66]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [67]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [68]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [69]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Possible data inputs to DataFrame constructor
* 2D ndarray
* dict of arrays, lists, or tuples
* NumPy structured/record array
* dict of Series, dict of dicts
* list of dicts or Series
* List of lists or tuples
* Another DataFrame
* NumPy MaskedArray

### Index Objects
- pandas’s Index objects are responsible for holding the axis labels

In [22]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [23]:
obj

a    0
b    1
c    2
dtype: int64

In [24]:
index = obj.index

In [25]:
index

Index(['a', 'b', 'c'], dtype='object')

In [26]:
index[1:]

Index(['b', 'c'], dtype='object')

- *Index objects can’t be modified by the user

In [28]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [76]:
index = pd.Index(np.arange(3))

In [77]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [78]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is index

True

- PeriodIndex : Specialized Index for Period data (timespans)

## Essential Functionality
### Reindexing

In [1]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

In [2]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

- ffill or pad: Fill (or carry) values forward
- bfill or backfill: Fill (or carry) values backward

In [7]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [15]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [9]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [10]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [11]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [12]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [13]:
states = ['Texas', 'Utah', 'California']

In [14]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill', columns=states)

 Texas Utah California
a  1   NaN   2
b  4   NaN   5
c  4   NaN   5
d  7   NaN   8

In [26]:
frame.ix[['a', 'b', 'c', 'd'], states]

/home/sooseok/Documents/.venv3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping entries from an axis

In [6]:
from pandas import Series
import numpy as np
obj = Series(np.arange(6.), index=['a', 'b', 'c', 'd', 'e', 'c'])

In [10]:
new_obj = obj.drop('c')

In [8]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [19]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [12]:
from pandas import DataFrame
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [13]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data.drop('two', axis=0)

ValueError: labels ['two'] not contained in axis

In [23]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

- axis=0: based on index(default) 
- axis=1: based on columns 
- ascending=True(default), ascending=False

### Indexing, selection, and filtering

In [38]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [39]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [17]:
print('!', obj['b'])
print('#', obj.loc['b'])

! 1.0
# 1.0


In [18]:
print('-', obj[1])
print('+', obj.iloc[1])

- 1.0
+ 1.0


In [27]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [28]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [29]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [30]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

- Slicing with labels behaves differently than normal Python slicing in that the endpoint is inclusive

In [32]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [33]:
obj['b':'c'] = 5

In [34]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [42]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [43]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data[['two']]

two
Ohio        0
Colorado    5
Utah        9
New York   13

In [45]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [46]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

- data which is greater tha data['three']

In [47]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [49]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [50]:
data[data < 5] = 0

In [51]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- obj.ix[val]: Selects single row of subset of rows from the DataFrame.
- obj.ix[:, val]: Selects single column of subset of columns.
- obj.ix[val1, val2]: Select both rows and columns.

In [19]:
data.ix['Colorado', ['two', 'three']]
data['Colorado', ['two', 'three']]

/home/sooseok/Documents/.venv3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


TypeError: unhashable type: 'list'

In [53]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [20]:
data.ix[2]
data[2]

KeyError: 2

In [55]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [56]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Arithmetic and data alignment

In [58]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [59]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [60]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [61]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [62]:
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [64]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [65]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [66]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

- Arithmetic methods with fill values

In [67]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [68]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [69]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [70]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [71]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

- fill_value: Substitute value to use when introducing missing data by reindexing

- add Method: for addition (+)
- sub Method: for subtraction (-)
- div Method: for division (/)
- mul Method: for multiplication (*)

In [78]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [81]:
df1.add(df2, fill_value=1)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   5.0
1   9.0  11.0  13.0  15.0  10.0
2  18.0  20.0  22.0  24.0  15.0
3  16.0  17.0  18.0  19.0  20.0

In [73]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

- Operations between DataFrame and Series

In [86]:
arr = np.arange(12.).reshape((3, 4))

In [87]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
arr[0]

array([0., 1., 2., 3.])

- ch.12 describes that in detail

In [85]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [89]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [90]:
series = frame.ix[0]

/home/sooseok/Documents/.venv3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [91]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [92]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

- By default, arithmetic between DataFrame and Series matches the index of the Series on the DataFrame's columns, broadcasting down the rows

- If an index value is not found in either the DataFrame’s columns or the Series’s index, the objects will be reindexed to form the union

In [93]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [94]:
series2 = Series(range(3), index=['b', 'e', 'f'])

In [95]:
series2

b    0
e    1
f    2
dtype: int64

In [96]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [97]:
series3 = frame['d']

In [98]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [99]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [100]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping

In [102]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [103]:
frame

b         d         e
Utah    0.118422 -2.262829 -2.232622
Ohio    1.243020  2.366038 -0.117336
Texas   0.014181 -0.748410  1.162040
Oregon  0.534288 -0.046766  0.608577

In [104]:
np.abs(frame)

b         d         e
Utah    0.118422  2.262829  2.232622
Ohio    1.243020  2.366038  0.117336
Texas   0.014181  0.748410  1.162040
Oregon  0.534288  0.046766  0.608577

In [105]:
f = lambda x: x.max() - x.min()

In [106]:
frame.apply(f)

b    1.228840
d    4.628867
e    3.394663
dtype: float64

In [107]:
frame.apply(f, axis=1)

Utah      2.381251
Ohio      2.483374
Texas     1.910450
Oregon    0.655343
dtype: float64

In [109]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [110]:
frame.apply(f)

b         d         e
min  0.014181 -2.262829 -2.232622
max  1.243020  2.366038  1.162040

In [111]:
format = lambda x: '%.2f' % x

In [112]:
frame.applymap(format)

b      d      e
Utah    0.12  -2.26  -2.23
Ohio    1.24   2.37  -0.12
Texas   0.01  -0.75   1.16
Oregon  0.53  -0.05   0.61

In [113]:
frame['e'].map(format)

Utah      -2.23
Ohio      -0.12
Texas      1.16
Oregon     0.61
Name: e, dtype: object